-- ============================================================================
-- HonuaIO AI Deployment Consultant - PostgreSQL Schema
-- ============================================================================
-- Database schema for deployment telemetry, pattern analysis, and knowledge base.
-- Supports supervised learning loop: telemetry → analysis → approval → RAG
--
-- Prerequisites:
--   - PostgreSQL 15+ with pgcrypto extension
--   - Run as database owner: psql -d honua -f schema.sql
-- ============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- Deployment History
-- ============================================================================
-- Stores complete telemetry for every deployment (successful or failed).
-- Used by PatternAnalysisFunction to identify successful patterns.

CREATE TABLE IF NOT EXISTS deployment_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    deployment_id VARCHAR(100) NOT NULL UNIQUE,
    customer_id VARCHAR(100) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Customer requirements (inputs)
    cloud_provider VARCHAR(50) NOT NULL,
    region VARCHAR(100) NOT NULL,
    data_volume_gb INTEGER NOT NULL,
    concurrent_users INTEGER NOT NULL,
    budget_monthly DECIMAL(10,2),

    -- Predicted values (from AI consultant)
    predicted_monthly_cost DECIMAL(10,2) NOT NULL,
    predicted_tile_response_p95_ms INTEGER NOT NULL,
    predicted_max_concurrent_users INTEGER NOT NULL,
    predicted_max_throughput_rps INTEGER NOT NULL,

    -- Actual measured values (post-deployment)
    actual_monthly_cost DECIMAL(10,2),
    actual_tile_response_p95_ms INTEGER,
    actual_concurrent_users INTEGER,
    actual_throughput_rps INTEGER,

    -- Accuracy metrics (calculated)
    cost_accuracy_percent DECIMAL(5,2),
    performance_accuracy_percent DECIMAL(5,2),

    -- Configuration (JSONB for flexibility)
    configuration JSONB NOT NULL,
    instance_type VARCHAR(100),
    database_instance_type VARCHAR(100),
    cache_instance_type VARCHAR(100),

    -- Outcome
    success BOOLEAN NOT NULL DEFAULT FALSE,
    required_rollback BOOLEAN NOT NULL DEFAULT FALSE,
    errors_encountered JSONB,
    duration_seconds INTEGER NOT NULL,
    customer_satisfied BOOLEAN,

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for pattern analysis queries
CREATE INDEX IF NOT EXISTS idx_deployment_history_cloud_provider ON deployment_history(cloud_provider);
CREATE INDEX IF NOT EXISTS idx_deployment_history_region ON deployment_history(region);
CREATE INDEX IF NOT EXISTS idx_deployment_history_timestamp ON deployment_history(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_deployment_history_success ON deployment_history(success);
CREATE INDEX IF NOT EXISTS idx_deployment_history_customer_id ON deployment_history(customer_id);
CREATE INDEX IF NOT EXISTS idx_deployment_history_instance_type ON deployment_history(instance_type);

-- Composite index for pattern grouping
CREATE INDEX IF NOT EXISTS idx_deployment_history_pattern_grouping
ON deployment_history(cloud_provider, region, instance_type, database_instance_type, cache_instance_type)
WHERE success = TRUE AND timestamp >= NOW() - INTERVAL '90 days';

-- ============================================================================
-- Pattern Recommendations
-- ============================================================================
-- Stores pattern recommendations generated by PatternAnalysisFunction.
-- Requires human approval before being indexed in Azure AI Search.

CREATE TABLE IF NOT EXISTS pattern_recommendations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    pattern_name VARCHAR(200) NOT NULL,
    cloud_provider VARCHAR(50) NOT NULL,
    region VARCHAR(100) NOT NULL,

    -- Configuration (exact configuration to recommend)
    configuration_json JSONB NOT NULL,

    -- Applicability ranges (when to use this pattern)
    applicability_json JSONB NOT NULL,

    -- Evidence (stats from deployments)
    evidence_json JSONB NOT NULL,

    -- Approval workflow
    status VARCHAR(50) NOT NULL DEFAULT 'pending_review', -- pending_review | approved | rejected
    analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reviewed_by VARCHAR(100),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    review_notes TEXT,

    -- Versioning
    version INTEGER NOT NULL DEFAULT 1,
    superseded_by UUID REFERENCES pattern_recommendations(id),

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    UNIQUE(pattern_name, cloud_provider)
);

-- Indexes for review workflow
CREATE INDEX IF NOT EXISTS idx_pattern_recommendations_status ON pattern_recommendations(status);
CREATE INDEX IF NOT EXISTS idx_pattern_recommendations_analyzed_at ON pattern_recommendations(analyzed_at DESC);
CREATE INDEX IF NOT EXISTS idx_pattern_recommendations_cloud_provider ON pattern_recommendations(cloud_provider);

-- ============================================================================
-- Pattern Interaction Feedback
-- ============================================================================
-- Stores detailed user interaction data for each pattern recommendation.
-- Tracks config modifications, timing, questions, and satisfaction for learning loop.

CREATE TABLE IF NOT EXISTS pattern_interaction_feedback (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    pattern_id VARCHAR(200) NOT NULL,
    deployment_id VARCHAR(100),

    -- Recommendation context
    recommended_at TIMESTAMP WITH TIME ZONE NOT NULL,
    recommendation_rank INTEGER NOT NULL,
    confidence_score DECIMAL(5,4) NOT NULL,

    -- User interaction timing
    decision_timestamp TIMESTAMP WITH TIME ZONE,
    time_to_decision_seconds INTEGER, -- How long user took to decide

    -- User decision
    was_accepted BOOLEAN,
    was_modified BOOLEAN NOT NULL DEFAULT FALSE,

    -- Configuration changes (what user changed from recommended config)
    recommended_config JSONB,
    actual_config JSONB,
    config_modifications JSONB, -- Structured diff of changes

    -- Interaction signals
    follow_up_questions_count INTEGER NOT NULL DEFAULT 0,
    user_hesitation_indicators JSONB, -- Backtracking, re-reading, etc.

    -- Explicit feedback
    user_satisfaction_rating INTEGER, -- 1-5 scale (optional)
    user_feedback_text TEXT,

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for learning analysis
CREATE INDEX IF NOT EXISTS idx_pattern_feedback_pattern_id ON pattern_interaction_feedback(pattern_id);
CREATE INDEX IF NOT EXISTS idx_pattern_feedback_recommended_at ON pattern_interaction_feedback(recommended_at DESC);
CREATE INDEX IF NOT EXISTS idx_pattern_feedback_accepted ON pattern_interaction_feedback(was_accepted);
CREATE INDEX IF NOT EXISTS idx_pattern_feedback_modified ON pattern_interaction_feedback(was_modified);
CREATE INDEX IF NOT EXISTS idx_pattern_feedback_satisfaction ON pattern_interaction_feedback(user_satisfaction_rating);

-- ============================================================================
-- Known Issues
-- ============================================================================
-- Stores known deployment issues for proactive troubleshooting.
-- Indexed in Azure AI Search for semantic search during deployments.

CREATE TABLE IF NOT EXISTS known_issues (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    issue_type VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    affected_regions VARCHAR(100)[],
    cloud_providers VARCHAR(50)[],
    trigger_conditions TEXT NOT NULL,
    solution TEXT NOT NULL,
    occurrence_count INTEGER NOT NULL DEFAULT 0,
    severity VARCHAR(20) NOT NULL DEFAULT 'medium', -- low | medium | high | critical

    -- Implementation tracking
    implemented BOOLEAN NOT NULL DEFAULT FALSE,
    implemented_date TIMESTAMP WITH TIME ZONE,
    implemented_by VARCHAR(100),

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for issue lookup
CREATE INDEX IF NOT EXISTS idx_known_issues_severity ON known_issues(severity);
CREATE INDEX IF NOT EXISTS idx_known_issues_implemented ON known_issues(implemented);
CREATE INDEX IF NOT EXISTS idx_known_issues_issue_type ON known_issues(issue_type);

-- ============================================================================
-- Agent Execution Metrics
-- ============================================================================
-- Tracks individual agent step performance for monitoring and optimization.

CREATE TABLE IF NOT EXISTS agent_execution_metrics (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    deployment_id VARCHAR(100) NOT NULL,
    agent_name VARCHAR(100) NOT NULL,
    action VARCHAR(200) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    duration_ms INTEGER,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    error_message TEXT,
    metadata JSONB,

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for performance analysis
CREATE INDEX IF NOT EXISTS idx_agent_execution_deployment_id ON agent_execution_metrics(deployment_id);
CREATE INDEX IF NOT EXISTS idx_agent_execution_agent_name ON agent_execution_metrics(agent_name);
CREATE INDEX IF NOT EXISTS idx_agent_execution_started_at ON agent_execution_metrics(started_at DESC);

-- ============================================================================
-- OpenAI Usage Tracking
-- ============================================================================
-- Tracks OpenAI API usage for cost monitoring and optimization.

CREATE TABLE IF NOT EXISTS openai_usage_tracking (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    deployment_id VARCHAR(100),
    operation VARCHAR(100) NOT NULL, -- chat_completion | embedding | etc
    model VARCHAR(100) NOT NULL,
    prompt_tokens INTEGER NOT NULL,
    completion_tokens INTEGER NOT NULL,
    total_tokens INTEGER NOT NULL,
    estimated_cost DECIMAL(10,6) NOT NULL,
    duration_ms INTEGER NOT NULL,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    error_message TEXT,

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for cost analysis
CREATE INDEX IF NOT EXISTS idx_openai_usage_deployment_id ON openai_usage_tracking(deployment_id);
CREATE INDEX IF NOT EXISTS idx_openai_usage_model ON openai_usage_tracking(model);
CREATE INDEX IF NOT EXISTS idx_openai_usage_created_at ON openai_usage_tracking(created_at DESC);

-- ============================================================================
-- Cost Optimization Recommendations
-- ============================================================================
-- Stores cost optimization recommendations sent to customers.

CREATE TABLE IF NOT EXISTS cost_optimization_recommendations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    customer_id VARCHAR(100) NOT NULL,
    deployment_id VARCHAR(100) NOT NULL,
    recommendation_type VARCHAR(100) NOT NULL, -- right_sizing | reserved_instances | etc
    recommendation_text TEXT NOT NULL,
    estimated_monthly_savings DECIMAL(10,2) NOT NULL,
    implemented BOOLEAN NOT NULL DEFAULT FALSE,
    implemented_date TIMESTAMP WITH TIME ZONE,
    actual_monthly_savings DECIMAL(10,2),

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for customer lookup
CREATE INDEX IF NOT EXISTS idx_cost_optimization_customer_id ON cost_optimization_recommendations(customer_id);
CREATE INDEX IF NOT EXISTS idx_cost_optimization_deployment_id ON cost_optimization_recommendations(deployment_id);
CREATE INDEX IF NOT EXISTS idx_cost_optimization_implemented ON cost_optimization_recommendations(implemented);

-- ============================================================================
-- Views for Analysis
-- ============================================================================

-- Pattern performance view (for human reviewers)
CREATE OR REPLACE VIEW pattern_performance AS
SELECT
    cloud_provider,
    region,
    instance_type,
    database_instance_type,
    cache_instance_type,
    COUNT(*) as deployment_count,
    AVG(CASE WHEN success THEN 1.0 ELSE 0.0 END) as success_rate,
    AVG(cost_accuracy_percent) as avg_cost_accuracy,
    AVG(performance_accuracy_percent) as avg_performance_accuracy,
    AVG(CASE WHEN customer_satisfied THEN 5.0 ELSE 0.0 END) as avg_customer_satisfaction,
    MIN(data_volume_gb) as min_data_volume,
    MAX(data_volume_gb) as max_data_volume,
    MIN(concurrent_users) as min_concurrent_users,
    MAX(concurrent_users) as max_concurrent_users,
    MIN(predicted_monthly_cost) as min_budget,
    MAX(predicted_monthly_cost) as max_budget
FROM deployment_history
WHERE timestamp >= NOW() - INTERVAL '90 days'
GROUP BY
    cloud_provider,
    region,
    instance_type,
    database_instance_type,
    cache_instance_type
HAVING COUNT(*) >= 5
ORDER BY success_rate DESC, deployment_count DESC;

-- OpenAI cost summary view
CREATE OR REPLACE VIEW openai_cost_summary AS
SELECT
    DATE(created_at) as date,
    model,
    operation,
    COUNT(*) as api_calls,
    SUM(total_tokens) as total_tokens,
    SUM(estimated_cost) as total_cost,
    AVG(duration_ms) as avg_duration_ms
FROM openai_usage_tracking
WHERE created_at >= NOW() - INTERVAL '30 days'
GROUP BY DATE(created_at), model, operation
ORDER BY date DESC, total_cost DESC;

-- Agent performance view
CREATE OR REPLACE VIEW agent_performance_summary AS
SELECT
    agent_name,
    action,
    COUNT(*) as execution_count,
    AVG(duration_ms) as avg_duration_ms,
    AVG(CASE WHEN success THEN 1.0 ELSE 0.0 END) as success_rate,
    COUNT(CASE WHEN NOT success THEN 1 END) as failure_count
FROM agent_execution_metrics
WHERE started_at >= NOW() - INTERVAL '30 days'
GROUP BY agent_name, action
ORDER BY execution_count DESC;

-- Pattern learning metrics view
CREATE OR REPLACE VIEW pattern_learning_metrics AS
SELECT
    pattern_id,
    COUNT(*) as total_recommendations,
    COUNT(*) FILTER (WHERE was_accepted = true) as accepted_count,
    COUNT(*) FILTER (WHERE was_modified = true) as modified_count,
    AVG(confidence_score) as avg_confidence,
    AVG(time_to_decision_seconds) as avg_decision_time_seconds,
    AVG(follow_up_questions_count) as avg_questions,
    AVG(user_satisfaction_rating) as avg_satisfaction,
    AVG(CASE WHEN was_accepted = true THEN 1.0 ELSE 0.0 END) as acceptance_rate,
    AVG(CASE WHEN was_modified = true THEN 1.0 ELSE 0.0 END) as modification_rate
FROM pattern_interaction_feedback
WHERE recommended_at >= NOW() - INTERVAL '90 days'
GROUP BY pattern_id
ORDER BY total_recommendations DESC;

-- Pattern confidence trends over time (weekly)
CREATE OR REPLACE VIEW pattern_confidence_trends AS
SELECT
    pattern_id,
    DATE_TRUNC('week', recommended_at) as week,
    COUNT(*) as recommendation_count,
    AVG(confidence_score) as avg_confidence,
    AVG(CASE WHEN was_accepted = true THEN 1.0 ELSE 0.0 END) as acceptance_rate,
    AVG(time_to_decision_seconds) as avg_decision_time
FROM pattern_interaction_feedback
WHERE recommended_at >= NOW() - INTERVAL '180 days'
GROUP BY pattern_id, DATE_TRUNC('week', recommended_at)
ORDER BY pattern_id, week DESC;

-- Feature importance analysis
CREATE OR REPLACE VIEW feature_importance_analysis AS
WITH config_changes AS (
    SELECT
        pattern_id,
        jsonb_object_keys(config_modifications) as changed_field,
        COUNT(*) as change_count
    FROM pattern_interaction_feedback
    WHERE was_modified = true
      AND config_modifications IS NOT NULL
      AND recommended_at >= NOW() - INTERVAL '90 days'
    GROUP BY pattern_id, jsonb_object_keys(config_modifications)
)
SELECT
    pattern_id,
    changed_field,
    change_count,
    ROUND((change_count::DECIMAL / SUM(change_count) OVER (PARTITION BY pattern_id)) * 100, 2) as change_percentage
FROM config_changes
ORDER BY pattern_id, change_count DESC;

-- ============================================================================
-- Functions
-- ============================================================================

-- Update timestamp trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to relevant tables
CREATE TRIGGER update_deployment_history_updated_at BEFORE UPDATE ON deployment_history
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_pattern_recommendations_updated_at BEFORE UPDATE ON pattern_recommendations
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_known_issues_updated_at BEFORE UPDATE ON known_issues
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_cost_optimization_updated_at BEFORE UPDATE ON cost_optimization_recommendations
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_pattern_interaction_feedback_updated_at BEFORE UPDATE ON pattern_interaction_feedback
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Sample Data (for testing)
-- ============================================================================

-- Insert a sample successful deployment
INSERT INTO deployment_history (
    deployment_id, customer_id, cloud_provider, region,
    data_volume_gb, concurrent_users, budget_monthly,
    predicted_monthly_cost, predicted_tile_response_p95_ms,
    predicted_max_concurrent_users, predicted_max_throughput_rps,
    actual_monthly_cost, actual_tile_response_p95_ms,
    actual_concurrent_users, actual_throughput_rps,
    cost_accuracy_percent, performance_accuracy_percent,
    configuration, instance_type, database_instance_type, cache_instance_type,
    success, duration_seconds, customer_satisfied
) VALUES (
    'test-deployment-001', 'customer-123', 'aws', 'us-west-2',
    500, 1000, 3000,
    2847, 150, 1500, 200,
    2912, 143, 1450, 195,
    97.77, 95.33,
    '{"instanceType": "m6i.2xlarge", "instanceCount": 2, "dbInstanceType": "db.r6g.xlarge", "cacheInstanceType": "cache.r6g.large"}'::jsonb,
    'm6i.2xlarge', 'db.r6g.xlarge', 'cache.r6g.large',
    true, 1275, true
) ON CONFLICT (deployment_id) DO NOTHING;

-- Insert a sample known issue
INSERT INTO known_issues (
    issue_type, description, affected_regions, cloud_providers,
    trigger_conditions, solution, occurrence_count, severity,
    implemented, implemented_date
) VALUES (
    'Database Connection Timeout',
    'PostgreSQL connections timeout intermittently in eu-west-1 during high load',
    ARRAY['eu-west-1'],
    ARRAY['aws'],
    'Data volume > 1TB AND concurrent users > 2000',
    'Increase max_connections to 200 and enable connection pooling with PgBouncer',
    15,
    'high',
    true,
    NOW() - INTERVAL '30 days'
) ON CONFLICT DO NOTHING;

-- ============================================================================
-- Permissions (adjust as needed)
-- ============================================================================

-- Grant permissions to application user
-- GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO honua_app_user;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO honua_app_user;
