// Copyright (c) 2025 HonuaIO
// Licensed under the Elastic License 2.0. See LICENSE file in the project root for full license information.
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Honua.Server.Core.Raster.Cache.Storage;

/// <summary>
/// Metadata describing a cached COG artifact in persistent storage.
/// </summary>
public sealed record CogStorageMetadata(string Uri, long SizeBytes, DateTime LastModifiedUtc);

/// <summary>
/// Abstraction over the physical storage backing the COG cache (filesystem, S3, Azure Blob, GCS, etc.).
/// </summary>
public interface ICogCacheStorage
{
    /// <summary>
    /// Try to retrieve metadata for an existing cached COG.
    /// </summary>
    /// <param name="cacheKey">Cache key generated by the raster cache service.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Metadata if the cached object exists; otherwise null.</returns>
    Task<CogStorageMetadata?> TryGetAsync(string cacheKey, CancellationToken cancellationToken = default);

    /// <summary>
    /// Persist a newly generated COG from a local staging file into the backing store.
    /// </summary>
    /// <param name="cacheKey">Cache key generated by the raster cache service.</param>
    /// <param name="localFilePath">Path to the staged COG on local disk.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Metadata describing the persisted artifact.</returns>
    Task<CogStorageMetadata> SaveAsync(string cacheKey, string localFilePath, CancellationToken cancellationToken = default);

    /// <summary>
    /// Remove a cached COG from the backing store.
    /// </summary>
    /// <param name="cacheKey">Cache key generated by the raster cache service.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task DeleteAsync(string cacheKey, CancellationToken cancellationToken = default);
}
