#!/bin/bash
# ============================================================================
# Setup Azure Terraform State Backend
# ============================================================================
# This script automates the setup of Azure Storage Account backend for
# Terraform state storage with blob lease locking.
#
# Usage:
#   ./setup-azure-backend.sh [options]
#
# Options:
#   -l, --location LOCATION       Azure region (default: eastus)
#   -g, --resource-group NAME     Resource group name (default: auto-generated)
#   -s, --storage-account NAME    Storage account name (default: auto-generated)
#   -c, --container NAME          Container name (default: tfstate)
#   -e, --environment ENV         Environment name (default: shared)
#   --enable-geo-replication      Enable geo-redundant storage (GRS)
#   --enable-private-endpoint     Enable private endpoint
#   --vnet-id VNET_ID            Virtual network ID (required for private endpoint)
#   --subnet-id SUBNET_ID        Subnet ID (required for private endpoint)
#   -h, --help                    Show this help message
# ============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
LOCATION="eastus"
RESOURCE_GROUP=""
STORAGE_ACCOUNT=""
CONTAINER_NAME="tfstate"
ENVIRONMENT="shared"
ENABLE_GEO_REPLICATION="false"
ENABLE_PRIVATE_ENDPOINT="false"
VNET_ID=""
SUBNET_ID=""

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(dirname "$SCRIPT_DIR")/azure"

# ============================================================================
# Functions
# ============================================================================

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

show_help() {
    head -n 22 "$0" | tail -n 19
    exit 0
}

check_prerequisites() {
    print_info "Checking prerequisites..."

    # Check Azure CLI
    if ! command -v az &> /dev/null; then
        print_error "Azure CLI not found. Please install: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
        exit 1
    fi

    # Check Terraform
    if ! command -v terraform &> /dev/null; then
        print_error "Terraform not found. Please install: https://www.terraform.io/downloads"
        exit 1
    fi

    # Check Azure login
    if ! az account show &> /dev/null; then
        print_error "Not logged in to Azure. Run 'az login'"
        exit 1
    fi

    # Validate private endpoint requirements
    if [ "$ENABLE_PRIVATE_ENDPOINT" = "true" ]; then
        if [ -z "$VNET_ID" ] || [ -z "$SUBNET_ID" ]; then
            print_error "Private endpoint requires --vnet-id and --subnet-id"
            exit 1
        fi
    fi

    print_success "All prerequisites met"
}

create_tfvars() {
    print_info "Creating terraform.tfvars file..."

    cat > "$BACKEND_DIR/terraform.tfvars" <<EOF
# Auto-generated by setup-azure-backend.sh
# Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

location                   = "$LOCATION"
environment                = "$ENVIRONMENT"
container_name             = "$CONTAINER_NAME"
enable_versioning          = true
enable_soft_delete         = true
soft_delete_retention_days = 30
enable_geo_replication     = $ENABLE_GEO_REPLICATION
allowed_ip_ranges          = []
enable_private_endpoint    = $ENABLE_PRIVATE_ENDPOINT
EOF

    if [ -n "$RESOURCE_GROUP" ]; then
        echo "resource_group_name        = \"$RESOURCE_GROUP\"" >> "$BACKEND_DIR/terraform.tfvars"
    fi

    if [ -n "$STORAGE_ACCOUNT" ]; then
        echo "storage_account_name       = \"$STORAGE_ACCOUNT\"" >> "$BACKEND_DIR/terraform.tfvars"
    fi

    if [ "$ENABLE_PRIVATE_ENDPOINT" = "true" ]; then
        echo "virtual_network_id         = \"$VNET_ID\"" >> "$BACKEND_DIR/terraform.tfvars"
        echo "subnet_id                  = \"$SUBNET_ID\"" >> "$BACKEND_DIR/terraform.tfvars"
    fi

    print_success "Created terraform.tfvars"
}

deploy_backend() {
    print_info "Deploying state backend infrastructure..."

    cd "$BACKEND_DIR"

    # Initialize Terraform
    print_info "Running terraform init..."
    terraform init

    # Plan
    print_info "Running terraform plan..."
    terraform plan -out=tfplan

    # Apply
    print_info "Running terraform apply..."
    terraform apply tfplan

    # Cleanup plan file
    rm -f tfplan

    print_success "Backend infrastructure deployed successfully"
}

save_outputs() {
    print_info "Saving backend configuration..."

    cd "$BACKEND_DIR"

    # Save JSON output
    terraform output -json > backend-config.json
    print_success "Saved backend-config.json"

    # Save HCL configuration
    terraform output -raw backend_config_hcl > backend-config.hcl
    print_success "Saved backend-config.hcl"

    # Save access key to file (secure)
    terraform output -raw storage_account_primary_access_key > .access_key
    chmod 600 .access_key
    print_success "Saved access key to .access_key (chmod 600)"

    # Extract key values
    RG=$(terraform output -raw resource_group_name)
    STORAGE=$(terraform output -raw storage_account_name)
    CONTAINER=$(terraform output -raw container_name)
    KV=$(terraform output -raw key_vault_name)

    # Display summary
    echo ""
    echo "============================================================================"
    print_success "Azure State Backend Setup Complete!"
    echo "============================================================================"
    echo ""
    echo "Backend Configuration:"
    echo "  Resource Group:  $RG"
    echo "  Storage Account: $STORAGE"
    echo "  Container:       $CONTAINER"
    echo "  Location:        $LOCATION"
    echo "  Key Vault:       $KV"
    echo ""
    echo "State Locking:"
    echo "  Azure uses blob leases for state locking (automatic, no extra config)"
    echo ""
    echo "Next Steps:"
    echo ""
    echo "  1. Set environment variable for access key:"
    echo "     export ARM_ACCESS_KEY=\$(cat $BACKEND_DIR/.access_key)"
    echo ""
    echo "  2. Copy backend configuration to your projects:"
    echo "     cp $BACKEND_DIR/backend-config.hcl <your-project>/backend.tf"
    echo ""
    echo "  3. Update the 'key' parameter for each project (use unique paths)"
    echo ""
    echo "  4. Initialize your project with backend migration:"
    echo "     cd <your-project>"
    echo "     terraform init -migrate-state"
    echo ""
    echo "Alternative authentication methods:"
    echo "  - Azure CLI: az login (recommended for development)"
    echo "  - Service Principal: Set ARM_CLIENT_ID, ARM_CLIENT_SECRET, etc."
    echo "  - Managed Identity: Set use_msi = true in backend config"
    echo ""
    echo "Files created:"
    echo "  - $BACKEND_DIR/terraform.tfvars"
    echo "  - $BACKEND_DIR/backend-config.json"
    echo "  - $BACKEND_DIR/backend-config.hcl"
    echo "  - $BACKEND_DIR/.access_key (sensitive, chmod 600)"
    echo ""
    echo "============================================================================"
}

# ============================================================================
# Parse Arguments
# ============================================================================

while [[ $# -gt 0 ]]; do
    case $1 in
        -l|--location)
            LOCATION="$2"
            shift 2
            ;;
        -g|--resource-group)
            RESOURCE_GROUP="$2"
            shift 2
            ;;
        -s|--storage-account)
            STORAGE_ACCOUNT="$2"
            shift 2
            ;;
        -c|--container)
            CONTAINER_NAME="$2"
            shift 2
            ;;
        -e|--environment)
            ENVIRONMENT="$2"
            shift 2
            ;;
        --enable-geo-replication)
            ENABLE_GEO_REPLICATION="true"
            shift
            ;;
        --enable-private-endpoint)
            ENABLE_PRIVATE_ENDPOINT="true"
            shift
            ;;
        --vnet-id)
            VNET_ID="$2"
            shift 2
            ;;
        --subnet-id)
            SUBNET_ID="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            ;;
        *)
            print_error "Unknown option: $1"
            show_help
            ;;
    esac
done

# ============================================================================
# Main
# ============================================================================

main() {
    echo "============================================================================"
    echo "Azure Terraform State Backend Setup"
    echo "============================================================================"
    echo ""

    check_prerequisites
    create_tfvars
    deploy_backend
    save_outputs
}

main
