#!/bin/bash
# ============================================================================
# Setup AWS Terraform State Backend
# ============================================================================
# This script automates the setup of AWS S3 + DynamoDB backend for Terraform
# state storage with locking.
#
# Usage:
#   ./setup-aws-backend.sh [options]
#
# Options:
#   -r, --region REGION           AWS region (default: us-east-1)
#   -b, --bucket BUCKET           S3 bucket name (default: auto-generated)
#   -t, --table TABLE             DynamoDB table name (default: honua-terraform-locks)
#   -e, --environment ENV         Environment name (default: shared)
#   --enable-replication          Enable cross-region replication
#   --replication-region REGION   Replication region (default: us-west-2)
#   --force-destroy               Allow bucket deletion with objects
#   -h, --help                    Show this help message
# ============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
REGION="us-east-1"
BUCKET_NAME=""
TABLE_NAME="honua-terraform-locks"
ENVIRONMENT="shared"
ENABLE_REPLICATION="false"
REPLICATION_REGION="us-west-2"
FORCE_DESTROY="false"

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(dirname "$SCRIPT_DIR")/aws"

# ============================================================================
# Functions
# ============================================================================

print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

show_help() {
    head -n 20 "$0" | tail -n 17
    exit 0
}

check_prerequisites() {
    print_info "Checking prerequisites..."

    # Check AWS CLI
    if ! command -v aws &> /dev/null; then
        print_error "AWS CLI not found. Please install: https://aws.amazon.com/cli/"
        exit 1
    fi

    # Check Terraform
    if ! command -v terraform &> /dev/null; then
        print_error "Terraform not found. Please install: https://www.terraform.io/downloads"
        exit 1
    fi

    # Check AWS credentials
    if ! aws sts get-caller-identity &> /dev/null; then
        print_error "AWS credentials not configured. Run 'aws configure' or set AWS_* environment variables"
        exit 1
    fi

    print_success "All prerequisites met"
}

create_tfvars() {
    print_info "Creating terraform.tfvars file..."

    cat > "$BACKEND_DIR/terraform.tfvars" <<EOF
# Auto-generated by setup-aws-backend.sh
# Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

region                        = "$REGION"
dynamodb_table_name          = "$TABLE_NAME"
environment                   = "$ENVIRONMENT"
enable_point_in_time_recovery = true
enable_bucket_replication     = $ENABLE_REPLICATION
replication_region            = "$REPLICATION_REGION"
force_destroy                 = $FORCE_DESTROY
EOF

    if [ -n "$BUCKET_NAME" ]; then
        echo "state_bucket_name            = \"$BUCKET_NAME\"" >> "$BACKEND_DIR/terraform.tfvars"
    fi

    print_success "Created terraform.tfvars"
}

deploy_backend() {
    print_info "Deploying state backend infrastructure..."

    cd "$BACKEND_DIR"

    # Initialize Terraform
    print_info "Running terraform init..."
    terraform init

    # Plan
    print_info "Running terraform plan..."
    terraform plan -out=tfplan

    # Apply
    print_info "Running terraform apply..."
    terraform apply tfplan

    # Cleanup plan file
    rm -f tfplan

    print_success "Backend infrastructure deployed successfully"
}

save_outputs() {
    print_info "Saving backend configuration..."

    cd "$BACKEND_DIR"

    # Save JSON output
    terraform output -json > backend-config.json
    print_success "Saved backend-config.json"

    # Save HCL configuration
    terraform output -raw backend_config_hcl > backend-config.hcl
    print_success "Saved backend-config.hcl"

    # Extract key values
    BUCKET=$(terraform output -raw state_bucket_name)
    TABLE=$(terraform output -raw dynamodb_table_name)
    REGION_OUT=$(terraform output -raw state_bucket_region)

    # Display summary
    echo ""
    echo "============================================================================"
    print_success "AWS State Backend Setup Complete!"
    echo "============================================================================"
    echo ""
    echo "Backend Configuration:"
    echo "  S3 Bucket:       $BUCKET"
    echo "  DynamoDB Table:  $TABLE"
    echo "  Region:          $REGION_OUT"
    echo ""
    echo "Next Steps:"
    echo "  1. Copy backend configuration to your projects:"
    echo "     cp $BACKEND_DIR/backend-config.hcl <your-project>/backend.tf"
    echo ""
    echo "  2. Update the 'key' parameter for each project (use unique paths)"
    echo ""
    echo "  3. Initialize your project with backend migration:"
    echo "     cd <your-project>"
    echo "     terraform init -migrate-state"
    echo ""
    echo "Files created:"
    echo "  - $BACKEND_DIR/terraform.tfvars"
    echo "  - $BACKEND_DIR/backend-config.json"
    echo "  - $BACKEND_DIR/backend-config.hcl"
    echo ""
    echo "============================================================================"
}

# ============================================================================
# Parse Arguments
# ============================================================================

while [[ $# -gt 0 ]]; do
    case $1 in
        -r|--region)
            REGION="$2"
            shift 2
            ;;
        -b|--bucket)
            BUCKET_NAME="$2"
            shift 2
            ;;
        -t|--table)
            TABLE_NAME="$2"
            shift 2
            ;;
        -e|--environment)
            ENVIRONMENT="$2"
            shift 2
            ;;
        --enable-replication)
            ENABLE_REPLICATION="true"
            shift
            ;;
        --replication-region)
            REPLICATION_REGION="$2"
            shift 2
            ;;
        --force-destroy)
            FORCE_DESTROY="true"
            shift
            ;;
        -h|--help)
            show_help
            ;;
        *)
            print_error "Unknown option: $1"
            show_help
            ;;
    esac
done

# ============================================================================
# Main
# ============================================================================

main() {
    echo "============================================================================"
    echo "AWS Terraform State Backend Setup"
    echo "============================================================================"
    echo ""

    check_prerequisites
    create_tfvars
    deploy_backend
    save_outputs
}

main
