// Copyright (c) 2025 HonuaIO
// Licensed under the Elastic License 2.0. See LICENSE file in the project root for full license information.
using System;
using System.Collections.Generic;
using Honua.Cli.AI.Secrets;

namespace Honua.Cli.AI.Services.Planning;

/// <summary>
/// Represents an execution plan generated by the AI assistant.
/// Similar to Terraform's plan, shows what will change before applying.
/// </summary>
public sealed class ExecutionPlan
{
    /// <summary>
    /// Unique identifier for this plan.
    /// </summary>
    public required string Id { get; init; }

    /// <summary>
    /// Human-readable title (e.g., "Optimize Database Performance").
    /// </summary>
    public required string Title { get; init; }

    /// <summary>
    /// Detailed description of what this plan accomplishes.
    /// </summary>
    public string? Description { get; init; }

    /// <summary>
    /// Type of plan (deployment, optimization, troubleshooting, etc.).
    /// </summary>
    public required PlanType Type { get; init; }

    /// <summary>
    /// Individual steps in the execution plan.
    /// </summary>
    public required List<PlanStep> Steps { get; init; }

    /// <summary>
    /// Credentials required for execution.
    /// </summary>
    public required List<CredentialRequirement> CredentialsRequired { get; init; }

    /// <summary>
    /// Assessment of the risk level for this plan.
    /// </summary>
    public required RiskAssessment Risk { get; init; }

    /// <summary>
    /// Rollback strategy if execution fails.
    /// </summary>
    public RollbackPlan? RollbackPlan { get; init; }

    /// <summary>
    /// When the plan was generated.
    /// </summary>
    public DateTime GeneratedAt { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// When the user approved the plan (null if not yet approved).
    /// </summary>
    public DateTime? ApprovedAt { get; set; }

    /// <summary>
    /// When the plan was applied (null if not yet applied).
    /// </summary>
    public DateTime? AppliedAt { get; set; }

    /// <summary>
    /// Current status of the plan.
    /// </summary>
    public PlanStatus Status { get; set; } = PlanStatus.Pending;

    /// <summary>
    /// Environment this plan targets (development, production, etc.).
    /// </summary>
    public string Environment { get; init; } = "development";
}

public enum PlanType
{
    Deployment,
    Optimization,
    Configuration,
    Troubleshooting,
    Migration,
    Backup,
    Recovery
}

public enum PlanStatus
{
    Pending,        // Generated, awaiting approval
    Approved,       // User approved, ready to apply
    Applying,       // Currently executing
    Completed,      // Successfully completed
    Failed,         // Execution failed
    RolledBack,     // Changes were rolled back
    Rejected        // User rejected the plan
}

/// <summary>
/// Represents a single step in an execution plan.
/// </summary>
public sealed class PlanStep
{
    /// <summary>
    /// Step identifier (1-based index).
    /// </summary>
    public required int StepNumber { get; init; }

    /// <summary>
    /// Human-readable description of this step.
    /// </summary>
    public required string Description { get; init; }

    /// <summary>
    /// Type of operation being performed.
    /// </summary>
    public required StepType Type { get; init; }

    /// <summary>
    /// The actual operation/command to execute.
    /// </summary>
    public required string Operation { get; init; }

    /// <summary>
    /// Expected outcome or benefit.
    /// </summary>
    public string? ExpectedOutcome { get; init; }

    /// <summary>
    /// Estimated duration for this step.
    /// </summary>
    public TimeSpan? EstimatedDuration { get; init; }

    /// <summary>
    /// Whether this step requires downtime.
    /// </summary>
    public bool RequiresDowntime { get; init; }

    /// <summary>
    /// Whether this step modifies data (vs. just schema/config).
    /// </summary>
    public bool ModifiesData { get; init; }

    /// <summary>
    /// Whether this step can be automatically reversed.
    /// </summary>
    public bool IsReversible { get; init; } = true;

    /// <summary>
    /// Dependencies (must execute after these step numbers).
    /// </summary>
    public List<int> DependsOn { get; init; } = new();

    /// <summary>
    /// Current status of this step.
    /// </summary>
    public StepStatus Status { get; set; } = StepStatus.Pending;

    /// <summary>
    /// When this step started executing.
    /// </summary>
    public DateTime? StartedAt { get; set; }

    /// <summary>
    /// When this step completed.
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Error message if step failed.
    /// </summary>
    public string? ErrorMessage { get; set; }
}

public enum StepType
{
    CreateIndex,
    DropIndex,
    UpdateConfig,
    CreateTable,
    AlterTable,
    CreateStatistics,
    VacuumAnalyze,
    Backup,
    Restore,
    Custom
}

public enum StepStatus
{
    Pending,
    Running,
    Completed,
    Failed,
    Skipped
}

/// <summary>
/// Credential requirement for plan execution.
/// </summary>
public sealed class CredentialRequirement
{
    /// <summary>
    /// Reference to the secret (e.g., "postgres-production").
    /// </summary>
    public required string SecretRef { get; init; }

    /// <summary>
    /// Scope of access needed.
    /// </summary>
    public required AccessScope Scope { get; init; }

    /// <summary>
    /// How long the credential will be needed.
    /// </summary>
    public required TimeSpan Duration { get; init; }

    /// <summary>
    /// Purpose/reason for needing this credential.
    /// </summary>
    public required string Purpose { get; init; }

    /// <summary>
    /// List of specific operations that will be performed.
    /// </summary>
    public required List<string> Operations { get; init; }
}


/// <summary>
/// Risk assessment for an execution plan.
/// </summary>
public sealed class RiskAssessment
{
    /// <summary>
    /// Overall risk level.
    /// </summary>
    public required RiskLevel Level { get; init; }

    /// <summary>
    /// Factors contributing to risk.
    /// </summary>
    public required List<string> RiskFactors { get; init; }

    /// <summary>
    /// Mitigation strategies.
    /// </summary>
    public required List<string> Mitigations { get; init; }

    /// <summary>
    /// Whether all changes are reversible.
    /// </summary>
    public bool AllChangesReversible { get; init; }

    /// <summary>
    /// Whether the plan requires downtime.
    /// </summary>
    public bool RequiresDowntime { get; init; }

    /// <summary>
    /// Estimated total downtime.
    /// </summary>
    public TimeSpan? EstimatedDowntime { get; init; }
}

public enum RiskLevel
{
    Low,        // Safe operations, fully reversible
    Medium,     // Some risk, requires approval
    High,       // Significant risk, requires explicit confirmation
    Critical    // Dangerous operations, may be blocked
}

/// <summary>
/// Rollback plan for undoing changes.
/// </summary>
public sealed class RollbackPlan
{
    /// <summary>
    /// Unique identifier for the rollback snapshot.
    /// </summary>
    public required string SnapshotId { get; init; }

    /// <summary>
    /// Steps to execute for rollback (in reverse order).
    /// </summary>
    public required List<RollbackStep> Steps { get; init; }

    /// <summary>
    /// When the snapshot was created.
    /// </summary>
    public DateTime CreatedAt { get; init; } = DateTime.UtcNow;
}

public sealed class RollbackStep
{
    /// <summary>
    /// Description of the rollback action.
    /// </summary>
    public required string Description { get; init; }

    /// <summary>
    /// The operation to execute for rollback.
    /// </summary>
    public required string Operation { get; init; }
}
